### ISSUE TITLE
整句回补建议

### ISSUE THREAD

**Issue by Hxdqdqp** [sbsrf/sbsrf-extra#2]
关于整句回补的，我想提个建议，就是现在数字键，是用了23789，之前在群里说的，23890更好用，可以考虑换成23890。

然后就是1键0键一个是定位右，一个定位末尾，然后‘键是二字节，但这样数字键还有3个没有用到，我觉得可以充分利用起来。

看看能不能将1保留，然后4用于二字节，5用于三字节，6用于四字节，7用于五字节利用起来，或者7承担0键的末尾。

这样14567五个键位可以用来回补，23890用来选重，由于4567是连在一起的，不会说区分不了。

另外‘键改成返回上个字节也行，因为试用1键定位修改的时候，总会不小心按过了头，这是因为它不是实时显示的。

往往按了之后就不知道是哪个字节是要改的了，像图上搜狗这样，他输入后就直接显示修改好的。

如果声笔也能做到这样，那么就不用按0键回到末尾才显示最终效果，也就不会出现突然按过头的情况了。

这样7键可以用来定位第五字节，如果还做不到这样的功能，那就将‘键改成返回上个字节吧。
![QQ图片20240306103718](https://github.com/sbsrf/sbsrf-extra/assets/162394790/f6f88e1e-565e-4af4-b7f5-bc7bca33d1ab)

**Comment by sbxlm** [comment]
现在已有的解决方式更好些
